export const products = [
  {
    id: "1",
    name: "Air Jordan 1 Retro High",
    price: 190,
    category: "Sneakers",
    brand: "Jordan",
    image: "https://images.unsplash.com/photo-1584000000000-000000000000?auto=format&fit=crop&q=80&w=800",
    description: "The Air Jordan 1 Retro High OG is a fan favorite, featuring the iconic silhouette and premium materials.",
    rating: 4.8,
    reviews: 120,
    sizes: [7, 8, 9, 10, 11, 12],
    colors: ["Red", "Black", "White"],
    isNew: true,
    isSale: false,
  },
  {
    id: "2",
    name: "Nike Air Max 270",
    price: 150,
    category: "Running",
    brand: "Nike",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800",
    description: "The Nike Air Max 270 delivers visible cushioning under every step for a smooth ride.",
    rating: 4.5,
    reviews: 85,
    sizes: [8, 9, 10, 11],
    colors: ["Black", "White"],
    isNew: false,
    isSale: true,
    salePrice: 120,
  },
  {
    id: "3",
    name: "Adidas Ultraboost 22",
    price: 180,
    category: "Running",
    brand: "Adidas",
    image: "https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&q=80&w=800",
    description: "The Ultraboost 22 provides energy return and a comfortable fit for long distance runs.",
    rating: 4.9,
    reviews: 210,
    sizes: [7, 8, 9, 10, 11],
    colors: ["Grey", "Black", "Blue"],
    isNew: true,
    isSale: false,
  },
  {
    id: "4",
    name: "Puma RS-X3",
    price: 110,
    category: "Sneakers",
    brand: "Puma",
    image: "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=800",
    description: "The Puma RS-X3 takes the retro silhouette to the next level with bold colors and textures.",
    rating: 4.3,
    reviews: 65,
    sizes: [8, 9, 10],
    colors: ["Multicolor"],
    isNew: false,
    isSale: false,
  },
  {
    id: "5",
    name: "Reebok Classic Leather",
    price: 85,
    category: "Lifestyle",
    brand: "Reebok",
    image: "https://images.unsplash.com/photo-1512374382149-433a72b9a5a5?auto=format&fit=crop&q=80&w=800",
    description: "A timeless classic that never goes out of style, perfect for everyday wear.",
    rating: 4.6,
    reviews: 150,
    sizes: [6, 7, 8, 9, 10, 11, 12],
    colors: ["White", "Black"],
    isNew: false,
    isSale: false,
  }
];
